name: ci

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push devcontainer stage
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          target: python-mrd-devcontainer
          push: true
          tags: |
            kspacekelvin/fire-python-devcon:latest
            kspacekelvin/fire-python-devcon:${{ github.ref_name }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: true
          tags: |
            kspacekelvin/fire-python:latest
            kspacekelvin/fire-python:${{ github.ref_name }}